generator:
  class: sfPropelGenerator
  param:
    model_class:           dcReportQuery
    theme:                 admin
    non_verbose_templates: true
    with_show:             true
    singular:              ~
    plural:                ~
    route_prefix:          dc_report_public
    with_propel_route:     1

    config:
      actions: ~
      fields:  ~
      list:    
        title: Reports
        max_per_page: 100
        display: [name]
        batch_actions: {}
        object_actions: 
          browse: 
            action: browseResults
            title: Browse results
        actions:  []
      filter:  
        class: false
      form:
        display: [] 
      edit:    
        title: Not Enabled
        display: []
      new:     
        title: Not Enabled
        display: []
