generator:
  class: sfPropelGenerator
  param:
    model_class:           dcReportField
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          dc_report_field
    with_propel_route:     1

    config:
      actions: ~
      fields:  
        dc_report_table: { label: Table }
        column_name: { label: Summary }
        group_selector: 
          label: Group By?
          help: ¿Group by this Column?
      list:    
        title: Columns Administration
        batch_actions: {}
        display: [ column_position, dc_report_table, column, alias, group_selector, handler_name, show_name, display_in_results, _column_name ]
        actions:
          query:
            label: Back to query
            action: backToQuery
          _new:
            label: Add Column
        object_actions:
          _edit:
          _delete:
      filter:  
        class: false
      form:
        fields:
          dc_report_table_id: 
            help: Select a table for real table columns. If empty you will create a custom field
            label: Report Table 
        display: [ dc_report_table_id, _column, handler, alias, group_selector, show_name, display_in_results, column_position ]
      edit:    
        title: Edit select fields
      new:  
        title: Edit select fields
        

